import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { isProduction } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getData() {
  const headers: Record<string, string> = {
    "Content-Type": "application/json",
  };
  if (isProduction()) {
    headers["Authorization"] = `Bearer ${process.env.STRAPI_API_TOKEN}`;
  }
  const res = await fetch(process.env.STRAPI_BASE_API_URL + "/graphql", {
    method: "POST",
    headers,
    body: JSON.stringify({
      query: `query {
  pages (filters:  {
     parent:  {
      documentId:  {
        null: true
      }        
     }
  }) {
    documentId
    title
    slug
    text
    publishedAt
    featuredImage {
      url
      alternativeText
    }
    children {
      title
      slug
      documentId
    }
  }
}`,
    }),
    cache: "no-store",
  });

  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }

  return res.json();
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { data } = await getData();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen flex-row md:flex-col md:overflow-hidden">
          <nav className="flex h-24 rounded-lg bg-white/80 backdrop-blur-sm relative gap-4 px-4">
            {data?.pages?.map((page: any) => (
              <div key={page.documentId} className="relative group h-full flex items-center">
                <a
                  href={page.slug}
                  className="block h-16 w-32 bg-cover bg-center rounded-md hover:scale-105 transition-transform"
                >
                  <div className="flex h-full items-end p-2 bg-gradient-to-t from-black/50 to-transparent rounded-md">
                    <span className="text-white font-bold text-xs group-hover:text-sm transition-all truncate">
                      {page.title}
                    </span>
                  </div>
                </a>

                {/* Subpages Menu Wrapper - ensures overlapping hit area to prevent collapse */}
                <div className="absolute left-full top-1/2 -translate-y-1/2 -ml-8 pl-8 hidden group-hover:block z-20">
                  <div className="flex flex-col min-w-[200px] bg-white/95 backdrop-blur-md rounded-lg shadow-2xl border border-gray-200 overflow-visible ml-2">
                    {page.children && page.children.length > 0 ? (
                      page.children.map((child: any) => (
                        <a
                          key={child.documentId}
                          href={child.slug}
                          className="px-4 py-3 text-sm font-semibold text-gray-700 hover:bg-blue-50 hover:text-blue-600 transition-colors border-b border-gray-100 last:border-0"
                        >
                          {child.title}
                        </a>
                      ))
                    ) : (
                      <>
                        <a href="#" className="px-4 py-3 text-sm font-semibold text-gray-700 hover:bg-blue-50 hover:text-blue-600 transition-colors border-b border-gray-100">
                          Placeholder Subpage 1
                        </a>
                        <a href="#" className="px-4 py-3 text-sm font-semibold text-gray-700 hover:bg-blue-50 hover:text-blue-600 transition-colors">
                          Placeholder Subpage 2
                        </a>
                      </>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </nav>
          <div className="grow p-6 md:overflow-y-auto md:p-12">{children}</div>
        </div>
      </body>
    </html>
  );
}
