import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { isProduction } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getData() {
  const headers: Record<string, string> = {
    "Content-Type": "application/json",
  };
  if (isProduction()) {
    headers["Authorization"] = `Bearer ${process.env.STRAPI_API_TOKEN}`;
  }
  const res = await fetch(process.env.STRAPI_BASE_API_URL + "/graphql", {
    method: "POST",
    headers,
    body: JSON.stringify({
      query: `query {
  pages (filters:  {
     parent:  {
      documentId:  {
        null: true
      }        
     }
  }) {
    documentId
    title
    slug
    text
    publishedAt
    featuredImage {
      url
      alternativeText
    }
    children {
      title
      slug
      documentId
    }
  }
}`,
    }),
    cache: "no-store",
  });

  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }

  return res.json();
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { data } = await getData();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen flex-row md:flex-col md:overflow-hidden">
          <nav className="flex h-24 overflow-hidden rounded-lg bg-white/80 backdrop-blur-sm">
            {data?.pages?.map((page: any) => (
              <a
                key={page.documentId}
                href={page.slug}
                className="flex-1 bg-cover bg-center hover:scale-105 transition-transform group"
              >
                <div className="flex h-full items-end p-4 bg-gradient-to-t from-black/50 to-transparent">
                  <span className="text-white font-bold text-sm group-hover:text-lg transition-all">
                    {page.title}
                  </span>
                </div>
              </a>
            ))}
          </nav>
          <div className="grow p-6 md:overflow-y-auto md:p-12">{children}</div>
        </div>
      </body>
    </html>
  );
}
